type Duration {
    years: Int
    months: Int
    days: Int
    hours: Int
    minutes: Int
    seconds: Float
}

type Coordinates {
    latitude: Float!
    longitude: Float!
}

type Route {
    routeNo: String!
    airplaneCode: String!
    daysOfWeek: [Int!]!
    scheduledTime: String!
    duration: Duration!
    departureCoordinates: Coordinates
    arrivalCoordinates: Coordinates
    departureAirport: Airport
    arrivalAirport: Airport
}

type RoutePage {
    data: [Route!]!
    page: Int!
    size: Int!
    hasMore: Boolean!
}

extend type Query {
    routes(
        page: Int = 1
        size: Int = 20
        airplaneCode: String
    ): RoutePage!
}